# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        name: Build Project
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
          - export PROJECT_NAME=src
          - dotnet restore src
          - dotnet build $PROJECT_NAME
    - step:
        name: Test Project
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
          - export TEST_NAME=test
          - dotnet restore test
          - dotnet test $TEST_NAME
    - step:
        name: Puplish Project
        deployment: production
        trigger: manual
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
          - dotnet help